# Created using wingetcreate 1.1.2.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.2.0.schema.json

PackageIdentifier: RedGateSoftwareLtd.RedgateInstaller
PackageVersion: 14.0
PackageLocale: en-US
Publisher: Red Gate Software Ltd
PackageName: SQL Developer Bundle
License: Licensed
Copyright: Copyright © Red Gate Software Ltd 2007-2021
ShortDescription: SQLDevBundle
ManifestType: defaultLocale
ManifestVersion: 1.2.0

